// Centralised icon proxy. The rest of the codebase imports from `@icons`
// (mapped in each app's tsconfig/vite alias) so we can swap the icon source
// in one place — currently lucide-react.
export {
  Home as IconHome,
  ChevronLeft as IconBack,
  ChevronRight as IconForward,
  User as IconUser,
  Search as IconSearch,
  Settings as IconSettings,
  LogOut as IconLogout,
  AlertTriangle as IconAlert,
  Activity as IconActivity,
  Map as IconMap,
  BarChart3 as IconChart,
  Zap as IconZap,
  Users as IconUsers,
  Wallet as IconMoney,
  Shield as IconShield,
  TrendingUp as IconTrending,
  TrendingDown as IconTrendingDown,
  Minus as IconSteady,
  Pin as IconPin,
  BadgeCheck as IconVerified,
  XCircle as IconFailed,
  Clock as IconPending,
  ChevronDown as IconChevronDown,
  ChevronUp as IconChevronUp,
  SlidersHorizontal as IconSliders,
  Play as IconRun,
  Save as IconSave,
  Copy as IconCopy,
  Download as IconDownload,
  Send as IconSend,
  MessageSquare as IconMessage,
  Flag as IconFlag,
  AlertCircle as IconWarning,
  BarChart2 as IconBarChart,
  PieChart as IconPieChart,
  Radio as IconLive,
  Globe as IconPublic,
  Lock as IconPrivate,
  SkipForward as IconSkip,
} from 'lucide-react';
